import json
import subprocess
import tempfile
from pathlib import Path

import pandas as pd

from pathlib import Path

def run_r_analysis(
    metadata,
    data_matrix,
    request,
    r_script=None
):
    """
    Send metadata, data matrix, and analysis request to R.

    Parameters
    ----------
    metadata : pandas.DataFrame
        Processed metadata.

    data_matrix : pandas.DataFrame
        Numeric outcome/features matrix.
        Each column is one outcome/feature.

    request : dict
        Analysis request generated by the UI/planner.

    r_script : str
        Path to run_analysis.R.

    Returns
    -------
    dict
        {
            "overall": pandas.DataFrame,
            "pairwise": pandas.DataFrame or None,
            "summary": dict,
            "r_stdout": str,
            "r_stderr": str
        }
    """

    # ========================================================
    # Temporary working directory
    #
    # Python writes inputs here.
    # R writes outputs here.
    #
    # Directory is automatically deleted after this
    # function finishes.
    # ========================================================

    with tempfile.TemporaryDirectory() as tmpdir:

        tmpdir = Path(tmpdir)

        # ----------------------------------------------------
        # Input files
        # ----------------------------------------------------

        metadata_path = (
            tmpdir / "metadata.csv"
        )

        data_matrix_path = (
            tmpdir / "data_matrix.csv"
        )

        request_path = (
            tmpdir / "request.json"
        )


        # ----------------------------------------------------
        # Output files
        # ----------------------------------------------------

        overall_path = (
            tmpdir / "overall_results.csv"
        )

        pairwise_path = (
            tmpdir / "pairwise_results.csv"
        )

        summary_path = (
            tmpdir / "summary.json"
        )


        # ====================================================
        # 1. Write metadata
        # ====================================================

        metadata.to_csv(
            metadata_path,
            index=False
        )


        # ====================================================
        # 2. Write outcome / omics matrix
        # ====================================================

        data_matrix.to_csv(
            data_matrix_path,
            index=False
        )


        # ====================================================
        # 3. Write request JSON
        # ====================================================

        with open(
            request_path,
            "w"
        ) as f:

            json.dump(
                request,
                f,
                indent=2
            )


        # ====================================================
        # 4. Build R command
        #
        # Corresponds to:
        #
        # Rscript R/run_analysis.R
        #     metadata.csv
        #     data_matrix.csv
        #     request.json
        #     overall_results.csv
        #     pairwise_results.csv
        #     summary.json
        # ====================================================

        if r_script is None:
            project_root = Path(__file__).resolve().parent.parent
            r_script = project_root / "R" / "run_analysis.R"

        r_script = Path(r_script)
        command = [
            "Rscript",
            str(r_script),
            str(metadata_path),
            str(data_matrix_path),
            str(request_path),
            str(overall_path),
            str(pairwise_path),
            str(summary_path)
        ]


        # ====================================================
        # 5. Run R
        # ====================================================

        process = subprocess.run(
            command,
            capture_output=True,
            text=True
        )


        # ====================================================
        # 6. Check whether the R process itself failed
        #
        # Feature-level failures inside the omics analysis
        # should NOT produce a non-zero return code because
        # model_runner.R catches those failures.
        #
        # This error means something more fundamental failed:
        # missing package, syntax error, invalid request, etc.
        # ====================================================

        if process.returncode != 0:

            raise RuntimeError(
                "R analysis failed.\n\n"
                f"STDOUT:\n{process.stdout}\n\n"
                f"STDERR:\n{process.stderr}"
            )


        # ====================================================
        # 7. Read primary / overall results
        # ====================================================

        if not overall_path.exists():

            raise RuntimeError(
                "R completed without creating "
                "overall_results.csv."
            )


        if overall_path.stat().st_size == 0:

            raise RuntimeError(
                "R created an empty overall results file."
            )


        overall = pd.read_csv(
            overall_path
        )


        # ====================================================
        # 8. Read pairwise results
        #
        # Pairwise is optional.
        #
        # Examples where it may be None:
        #
        # numeric predictor
        # binary categorical predictor
        # ordered categorical predictor
        # trajectory analysis without pairwise output
        # ====================================================

        pairwise = None


        if (
            pairwise_path.exists()
            and pairwise_path.stat().st_size > 0
        ):

            try:

                pairwise = pd.read_csv(
                    pairwise_path
                )

            except pd.errors.EmptyDataError:

                pairwise = None


        # ====================================================
        # 9. Read analysis summary
        #
        # Contains information such as:
        #
        # analysis_type
        # analysis_goal
        # convergence_fraction
        # singular_fraction
        # final_random_slope
        # rerun
        # ====================================================

        summary = {}


        if (
            summary_path.exists()
            and summary_path.stat().st_size > 0
        ):

            with open(
                summary_path,
                "r"
            ) as f:

                summary = json.load(
                    f
                )


        # ====================================================
        # 10. Return everything to app.py
        # ====================================================

        return {

            "overall":
                overall,

            "pairwise":
                pairwise,

            "summary":
                summary,

            # Useful for debugging / diagnostics
            "r_stdout":
                process.stdout,

            "r_stderr":
                process.stderr
        }




